import baseLogin from "../support/PageObject/loginPage.cy"
const loginData = require("../fixtures/OrangeHrm/login.json")

describe('Login Fuctionality', () => {
  const BaseLogin = new baseLogin()
  it('successLogin', () => {
    cy.visit(loginData.url)
    BaseLogin.inputUsername(loginData.validUser)
    BaseLogin.inputPassword(loginData.validPass)
    BaseLogin.clickLogin()
    BaseLogin.verifSucces()
    BaseLogin.verifUrl()
    // cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('be.visible')
    // cy.url().should('include','/web/index.php/dashboard/index')
  })
  it('loginInvalidUsername', () => {
    cy.visit(loginData.url)
    // cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type("Sandi")
    BaseLogin.inputUsername(loginData.invalidUser)
    // cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type("admin123")
    BaseLogin.inputPassword(loginData.validPass)
    BaseLogin.clickLogin()
    cy.get('.oxd-alert-content > .oxd-text').should('be.visible')
  })
   it('loginInvalidPassword', () => {
    cy.visit(loginData.url)
    // cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type("Admin")
    BaseLogin.inputUsername(loginData.validUser)
    // cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type("12345")
    BaseLogin.inputPassword(loginData.invalidPass)
    BaseLogin.clickLogin()
    cy.get('.oxd-alert-content > .oxd-text').should('be.visible')
  })
  it('loginEmptyEmail', () => {
    cy.visit(loginData.url)
    BaseLogin.inputUsername(loginData.emptyUser)
    // cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type(" ")
    // cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type("12345")
    BaseLogin.inputPassword(loginData.validPass)
    BaseLogin.clickLogin()
    cy.get('.oxd-input-group > .oxd-text').should('be.visible')
  })
  it('loginEmptyPassword', () => {
    cy.visit(loginData.url)
    BaseLogin.inputUsername(loginData.validUser)
    cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type("Admin")
    BaseLogin.inputPassword(loginData.emptyPass)
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type(" ")
    BaseLogin.clickLogin()
    cy.get('.oxd-input-group > .oxd-text').should('be.visible')
  })
})